services:
  - type: web
    name: OmniMindUltimate
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -b 0.0.0.0:$PORT main:app
    envVars:
      - key: SECRET_KEY
        value: "your-secret-key"
      - key: DATABASE_URL
        value: "your-database-url"
